apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/aiboosts/YoBot'
    targetRevision: HEAD
    path: 'k8s-manifests'
  project: default
