apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/aiboosts/hello-docker-gcr-demo:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: ghcr-secret  # Das ImagePullSecret, das du vorher erstellt hast
