name: publish

on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build the hello-docker Docker image
        run: |
          docker build -t ghcr.io/yobot/hello-docker-gcr-demo:latest .
          docker run ghcr.io/yobot/hello-docker-gcr-demo:latest

      # Push the Docker image to GHCR
      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/yobot/hello-docker-gcr-demo:latest
