name: publish

on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}  # Use GHCR_TOKEN secret here

      # Build the Docker image
      - name: Build the hello-docker Docker image
        run: |
          docker build -t ghcr.io/aiboosts/hello-docker-gcr-demo:latest .
          docker run ghcr.io/aiboosts/hello-docker-gcr-demo:latest

      # Trivy Scan for vulnerabilities in the Docker image
      - name: Trivy Scan for vulnerabilities
        uses: aquasecurity/trivy-action@v0.30.0
        with:
          image: ghcr.io/aiboosts/hello-docker-gcr-demo:latest
        env:
          TRIVY_SEVERITY: HIGH,CRITICAL  # Optional: You can set severity levels to scan for

      # Push the Docker image to GitHub Container Registry
      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/aiboosts/hello-docker-gcr-demo:latest
