name: YoBot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Build & Push
        run: |
          docker build -t ${{ secrets.GITHUB_TOKEN }}/yobot:latest .
          docker push ${{ secrets.GITHUB_TOKEN }}/yobot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          echo "Tests abgeschlossen! Fehler? Nö. 😎"

  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Log Analyse mit Ollama
        run: |
          curl -s http://localhost:11434/api/generate \
          -d '{"model": "llama3", "prompt": "Analysiere diesen Kubernetes-Fehler sarkastisch: [ERROR] Pod failed due to OOM!", "stream": false}'
